### ISSUE TITLE
Remover o diretório __MACOSX desnessário

### ISSUE THREAD

**Issue by fabriciofx** [AlderiAraujo/DSWI#1]
Remover o diretório __MACOSX desnecessário. Se for preciso, adicioná-lo no `.gitignore`.

**Comment by AlderiAraujo** [comment]
@fabriciofx todas as adequações conforme solicitados nas Issues foram realizadas, aguardando reavaliação para fechamento das Issues.

**Comment by fabriciofx** [comment]
@AlderiAraujo ok!
