### ISSUE TITLE
Colocar o menu de navegação dentro de um header

### ISSUE THREAD

**Issue by fabriciofx** [AlderiAraujo/DSWI#4]
Coloca o menu de navegação dentro de um `<header>` em todas as páginas.

**Comment by fabriciofx** [comment]
@AlderiAraujo Eu não sei se você trocou o `<nav>` pelo `<header>`, mas deveria ter um `<nav>` dentro de um `<header>` dentro de cada menu. Favor corrigir.

**Comment by AlderiAraujo** [comment]
entendido @fabriciofx , acabei de realizar a adequação conforme orientado.

**Comment by fabriciofx** [comment]
@AlderiAraujo ok!
