### ISSUE TITLE
Colocar todo o código no main

### ISSUE THREAD

**Issue by fabriciofx** [AlderiAraujo/DSWI#6]
Colocar todo o código do formulário na tag `<main>` (não só o `<h1>`).

**Comment by AlderiAraujo** [comment]
@fabriciofx o código foi atualizado conforme as solicitações, aguardando nova correção.

**Comment by fabriciofx** [comment]
@AlderiAraujo No arquivo `home.html` ainda tem um parágrafo fora do `<main>`.

**Comment by AlderiAraujo** [comment]
@fabriciofx código atualizado conforme as novas exigências das Issues 6 e 10, aguardando nova avaliação

**Comment by fabriciofx** [comment]
@AlderiAraujo ok!
