### ISSUE TITLE
Não usar o input do tipo tel para cep

### ISSUE THREAD

**Issue by fabriciofx** [AlderiAraujo/DSWI#8]
Não usar o input do tipo tel para cep.

**Comment by fabriciofx** [comment]
@AlderiAraujo o mais indicado para o cep seria o `input` do tipo `text`. Além disso, você deveria ter os atributos `id` e `name` para este `input`.

**Comment by AlderiAraujo** [comment]
@fabriciofx código atualizado conforme solicitações nas Issues 8 e 11, no aguardo de nova avaliação.

**Comment by fabriciofx** [comment]
@AlderiAraujo feito!
